version: '3'

services:
  bot:
    image: reimashi/open-torrent-tracker-bot:latest
    environment:
      DEBUG: 0
      TELEGRAM_TOKEN:
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASS: example
    depends_on:
    - "db"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  db:
    image: mongo:latest
    volumes:
    - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    labels:
    - com.centurylinklabs.watchtower.enable="true"
  updater:
    image: v2tec/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - updater:/config.json
    command: --interval 3600 --label-enable
    restart: always
    labels:
    - com.centurylinklabs.watchtower.enable="true"

volumes:
  database:
  updater:
